packages:
  - packages/*

catalog:
  eslint: ^9.37.0
  tsup: ^8.4.0
  typescript: ^5.9.3
  "@swc/core": 1.13.5
  "@types/eslint": ^9.6.1
  "@types/node": ^24.7.0
  "@zemd/tsconfig": ^1.4.0
  eslint-plugin-react-refresh: ^0.4.23

overrides:
  brace-expansion@>=1.0.0 <=1.1.11: ">=1.1.12"
  brace-expansion@>=2.0.0 <=2.0.1: ">=2.0.2"
