packages:
  - "packages/*"

catalog:
  "eslint": "^9.21.0"
  "tsup": "^8.3.6"
  "typescript": ^5.7.3
  "@swc/core": "1.11.1"
  "@types/eslint": "^9.6.1"
  "@types/node": "^22.13.5"
  "@zemd/tsconfig": "^1.3.0"
  "eslint-plugin-react-refresh": ^0.4.19
