packages:
  - "packages/*"

catalog:
  "eslint": "^9.18.0"
  "tsup": "^8.3.5"
  "typescript": ^5.7.3
  "@swc/core": "1.10.4"
  "@types/eslint": "^9.6.1"
  "@types/eslint__js": "^8.42.3"
  "@types/node": "^22.10.2"
  "@zemd/tsconfig": "^1.3.0"
