packages:
  - "packages/*"

catalog:
  "eslint": "^9.20.1"
  "tsup": "^8.3.6"
  "typescript": ^5.7.3
  "@swc/core": "1.10.16"
  "@types/eslint": "^9.6.1"
  "@types/eslint__js": "^8.42.3"
  "@types/node": "^22.13.2"
  "@zemd/tsconfig": "^1.3.0"
  "eslint-plugin-react-refresh": ^0.4.19
