name: Update readme

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  update_readme:
    if: github.actor == 'zemd'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          run_install: false

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Update readme
        run: pnpm readme

      - name: Format
        run: pnpm format

      - name: Commit readme
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update readme"

      - name: Push changes
        run: git push origin HEAD
